version: 0.2

phases:
  install:
    commands:
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn build
  post_build:
    commands:
    - aws s3 rm s3://popcycle-parking-page -r
artifacts:
  base-directory: dist
  files:
    - '**/*'
cache:
  paths:
    - node_modules
